/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include "OS.h"
#include "Externs.h"

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}


void _API(int id)
{

	if(id == 199)
	{

			ActivateTask(199);
			__asm volatile(
														"MOV sp, %0 \n\t"

														:
														: "r" (&OsTasksPCB[199]->sp)
														: "memory"
												  );
			 __asm volatile (
				        "MOV lr, %0\n\t"   // Move the address to jump to into register R0
				        "BX lr;"// Branch to the address in R0 (task1.address)
				        :
				        : "r" (OsTasksPCB[199]->address)
				        : "memory"
				    );

	}
	if(id == 1)
	{


					__asm volatile(
							"PUSH {r0-r12,lr};"
							"MOV %0, sp\n\t"
							: "=r" (OsTasksPCB[199]->sp)
							:
							: "memory"
							);

					ActivateTask(0);
				    __asm volatile(
						"MOV sp, %0 \n\t"

						:
				    	: "r" (&OsTasksPCB[0]->sp)
						: "memory"

				    );
					 __asm volatile (
									        "MOV lr, %0\n\t"   // Move the address to jump to into register R0
							 "BX lr;"// Branch to the address in R0 (task1.address)
									        :
									        : "r" (OsTasksPCB[0]->address)
									        : "memory"
				    );


	}
	if(id == 2)
	{
		TerminateTask();
		uint32_t temp;
		__asm volatile(
																"MOV sp, %0 \n\t"

																:
																: "r" (&OsTasksPCB[199]->sp)
																: "memory"
		           );
		__asm volatile(
								"POP {r0-r12,lr};"
								"MOV %0, sp\n\t"
								: "=r" (temp)
								:
								: "memory"
								);
		OsTasksPCB[199]->sp = temp;
	}




}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file)
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
